### ISSUE TITLE
113-1 websites

### ISSUE THREAD

**Issue by Jung217** [Jung217/JengYeh_WEB#1]
### Paste your own github page url here.
* 簡志融
https://jung217.github.io/JengYeh_WEB/me.html

**Comment by Jung217** [comment]
* 葉哲辰
https://yehchen0328.github.io/JengYeh_WEB/me.html

**Comment by Jung217** [comment]
* 林家成
https://ali1234-56.github.io/JengYeh_WEB/me.html

**Comment by Mikey104024** [comment]
* 辰義豐
https://mikey104024.github.io/JengYeh_WEB/me.html

**Comment by Doris1040722** [comment]
* 葉紜羽
https://doris1040722.github.io/JengYeh_WEB/me.html

**Comment by Jack1030719** [comment]
* 李泉樑 
https://jack1030719.github.io/JengYeh_WEB/me.html

> 改網站名、多"正義國小"

**Comment by Rapunzel02109** [comment]
* 陳宥蓉
https://rapunzel02109.github.io/JengYeh_WEB/me.html

**Comment by belle1836** [comment]
* 莊筠媗
https://belle1836.github.io/JengYeh_WEB/me.html

**Comment by UT0507** [comment]
* 陳禹潼
https://ut0507.github.io/JengYeh_WEB/me.html

**Comment by belle1836** [comment]
https://belle1836.github.io/JengYeh_WEB/me.html

**Comment by Ping1040425** [comment]
* 王憶萍
https://ping1040425.github.io/JengYeh_WEB/me.html

**Comment by hyx0406** [comment]
* 黃以璇
https://hyx0406.github.io/JengYeh_WEB/me.html

#000000

**Comment by yuchen1030505** [comment]
- 董羽宸
 https://yuchen1030505.github.io/JengYeh_WEB/me.html

**Comment by ali1234-56** [comment]
<style>
        @keyframes anforh2 {
          0% { color: red; }
          20% { color: orange; } 
          40% { color: #ffcc00; }
          60% { color: green; }
          80% { color: blue; }
          100% { color: purple; }
        }
        .title{
            animation-name: anforh2;
            animation-duration: 5s;
            animation-iteration-count: infinite;
        }
        body {
            border: 10px ridge;
            padding: 20px;
        }
      </style>

**Comment by Jung217** [comment]
.navbar {
    background-color: #333;
    padding: 10px 20px;
}

.nav1 {
    list-style: none;
    display: flex;
    gap: 15px;
}

.nav1 a {
    text-decoration: none;
    color: white;
    padding: 8px 15px;
}

.nav1 a:hover {
    background-color: #575757;
    border-radius: 10px;
}

**Comment by simon0983** [comment]
杜翁松甫
https://simon0983.github.io/JengYeh_WEB/me.html

**Comment by Jung217** [comment]
> The class dismissed on 2024.12.25.
